-- knowledge-mcp schema. Idempotent: runs on every boot with spring.sql.init.mode=always.

CREATE TABLE IF NOT EXISTS knowledge_pattern (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- hash of (category, scope, normalized statement): the identity of a rule
    fingerprint     VARCHAR(64)  NOT NULL UNIQUE,
    category        VARCHAR(32)  NOT NULL,
    scope           VARCHAR(16)  NOT NULL,
    project_key     VARCHAR(160),
    statement       VARCHAR(2000) NOT NULL,
    anti_pattern    VARCHAR(2000),
    rationale       VARCHAR(2000),
    tags            VARCHAR(400),
    status          VARCHAR(16)  NOT NULL,
    hit_count       INT          NOT NULL,
    confidence      DOUBLE       NOT NULL,
    first_seen_at   TIMESTAMP(3) NOT NULL,
    last_seen_at    TIMESTAMP(3) NOT NULL,
    author          VARCHAR(120),
    source_ref      VARCHAR(400),
    superseded_by   BIGINT,
    archived_reason VARCHAR(400)
);

CREATE INDEX IF NOT EXISTS idx_pattern_status  ON knowledge_pattern(status);
CREATE INDEX IF NOT EXISTS idx_pattern_bucket  ON knowledge_pattern(category, scope);
CREATE INDEX IF NOT EXISTS idx_pattern_project ON knowledge_pattern(project_key);

-- One row per sighting. This is what makes a promoted rule auditable instead of
-- just asserted: it answers "why does this rule exist" months later.
CREATE TABLE IF NOT EXISTS pattern_evidence (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern_id  BIGINT       NOT NULL,
    note        VARCHAR(4000),
    author      VARCHAR(120),
    source_ref  VARCHAR(400),
    -- 1.0 for an exact match, lower when folded in by near-duplicate detection
    similarity  DOUBLE       NOT NULL,
    recorded_at TIMESTAMP(3) NOT NULL,
    CONSTRAINT fk_evidence_pattern FOREIGN KEY (pattern_id)
        REFERENCES knowledge_pattern(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_evidence_pattern ON pattern_evidence(pattern_id);
